version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: build.sh
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: 
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 300
      runas: root
  # ApplicationStop:
  #   - location: 
  #     timeout: 300
  #     runas: root
